apiVersion: 1

datasources:
  - name: Postgres - rover_mars
    uid: rover_postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
